# Generated by Django 5.1 on 2024-09-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('VIN', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('year', models.IntegerField()),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('dateBirdth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportNumber', models.CharField(max_length=10)),
                ('dateBirdth', models.DateField()),
                ('dateIssue', models.DateField()),
                ('code', models.CharField(max_length=7)),
                ('institution', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=30)),
                ('registration', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskType', models.CharField(max_length=30)),
                ('season', models.CharField(max_length=30)),
                ('tireWidth', models.IntegerField()),
                ('tireHeight', models.IntegerField()),
                ('tireDiameter', models.IntegerField()),
                ('tireManufacture', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wheel',
            },
        ),
        migrations.CreateModel(
            name='DDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=20)),
                ('operationDate', models.DateField()),
                ('amount', models.FloatField()),
                ('paymentAccount', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('isProfit', models.BooleanField()),
                ('carId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars')),
                ('employeeId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.employees')),
            ],
            options={
                'db_table': 'dds',
            },
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticDate', models.DateField()),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=255, null=True)),
                ('transmission', models.CharField(blank=True, max_length=255, null=True)),
                ('suspension', models.CharField(blank=True, max_length=255, null=True)),
                ('tires', models.CharField(blank=True, max_length=255, null=True)),
                ('steering', models.CharField(blank=True, max_length=255, null=True)),
                ('brake', models.CharField(blank=True, max_length=255, null=True)),
                ('electrical', models.CharField(blank=True, max_length=255, null=True)),
                ('climate', models.CharField(blank=True, max_length=255, null=True)),
                ('dasboard', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostics', models.TextField(blank=True, null=True)),
                ('windshield', models.CharField(blank=True, max_length=255, null=True)),
                ('PZD', models.IntegerField(blank=True, null=True)),
                ('PPD', models.IntegerField(blank=True, null=True)),
                ('PPK', models.IntegerField(blank=True, null=True)),
                ('PZK', models.IntegerField(blank=True, null=True)),
                ('PB', models.IntegerField(blank=True, null=True)),
                ('ZB', models.IntegerField(blank=True, null=True)),
                ('KAP', models.IntegerField(blank=True, null=True)),
                ('KRH', models.IntegerField(blank=True, null=True)),
                ('KB', models.IntegerField(blank=True, null=True)),
                ('LZK', models.IntegerField(blank=True, null=True)),
                ('LPK', models.IntegerField(blank=True, null=True)),
                ('LZD', models.IntegerField(blank=True, null=True)),
                ('LPD', models.IntegerField(blank=True, null=True)),
                ('factoryLKP', models.IntegerField(blank=True, null=True)),
                ('descriptionLKP', models.CharField(blank=True, max_length=255, null=True)),
                ('testdrive', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('autoteka', models.URLField()),
                ('carId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars')),
                ('employeeId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.employees')),
            ],
            options={
                'db_table': 'diagnostic',
            },
        ),
        migrations.CreateModel(
            name='KanbanCols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('stage', models.CharField(max_length=20)),
                ('cross', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.kanbancols')),
            ],
            options={
                'db_table': 'kanban',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='stageId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.kanbancols'),
        ),
        migrations.CreateModel(
            name='PrebuyCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prebuyDate', models.DateField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('typeSourse', models.CharField(max_length=30)),
                ('carSourse', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('prepositionNote', models.TextField(blank=True, null=True)),
                ('carCost', models.IntegerField()),
                ('marginality', models.FloatField()),
                ('predictCost', models.IntegerField()),
                ('liquidRatio', models.IntegerField(blank=True, null=True)),
                ('carId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars')),
                ('employeeId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.employees')),
            ],
            options={
                'db_table': 'prebuy_car',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('taskDate', models.DateField()),
                ('completeDate', models.DateTimeField()),
                ('carId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars')),
                ('employeeId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.employees')),
                ('stageId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.kanbancols')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='BuyCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', models.IntegerField(blank=True, null=True)),
                ('govNum', models.CharField(blank=True, max_length=9, null=True)),
                ('typePTS', models.CharField(blank=True, max_length=20, null=True)),
                ('cntKeys', models.IntegerField(blank=True, null=True)),
                ('carId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars')),
                ('ddsId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.dds')),
                ('entityId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.entities')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.wheels')),
            ],
            options={
                'db_table': 'buy_car',
            },
        ),
    ]
