# Generated by Django 5.1 on 2024-10-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancols',
            name='cross',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.kanbancols'),
        ),
    ]
