# Generated by Django 5.1 on 2024-10-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_cars_brand_alter_cars_model_alter_cars_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebuycars',
            name='carSourse',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
