# Generated by Django 5.1 on 2024-10-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_prebuycars_carsourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycars',
            name='entityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.entities'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='stageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.kanbancols'),
        ),
        migrations.AlterField(
            model_name='dds',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='dds',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.employees'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.employees'),
        ),
        migrations.AlterField(
            model_name='prebuycars',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.employees'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.employees'),
        ),
    ]
