# Generated by Django 5.1 on 2024-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_buycars_entityid_alter_cars_stageid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'car_source',
            },
        ),
        migrations.CreateModel(
            name='ClientSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'client_source',
            },
        ),
        migrations.CreateModel(
            name='DDSAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'dds_account',
            },
        ),
        migrations.CreateModel(
            name='MoneyArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('isProfit', models.BooleanField()),
            ],
            options={
                'db_table': 'money_article',
            },
        ),
    ]
