# Generated by Django 5.1 on 2024-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_carsources_clientsources_ddsaccounts_moneyarticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycars',
            name='tire',
        ),
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/'),
        ),
    ]
