# Generated by Django 5.1 on 2024-10-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_buycars_tire_alter_cars_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100)),
                ('positionName', models.CharField(max_length=100)),
                ('widgetName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'widget',
            },
        ),
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='EmployeeWidgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.employees')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.widgets')),
            ],
        ),
    ]
