# Generated by Django 5.1 on 2024-10-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_widgets_alter_cars_photo_employeewidgets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeewidgets',
            name='widget',
        ),
        migrations.AddField(
            model_name='employeewidgets',
            name='widget',
            field=models.ManyToManyField(to='cars.widgets'),
        ),
    ]
