# Generated by Django 5.1 on 2024-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_employeewidgets_widget_employeewidgets_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='article',
            field=models.CharField(max_length=100),
        ),
    ]
