# Generated by Django 5.1 on 2024-10-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_dds_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='carId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cars'),
        ),
    ]
